version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY}
      - DEBUG=${DEBUG}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
